diff -uNr bcrypt-1.8-3-orig/Makefile bcrypt-1.8-3/Makefile
--- bcrypt-1.8-3-orig/Makefile	2010-09-13 11:21:20.000000000 -0400
+++ bcrypt-1.8-3/Makefile	2011-01-07 14:48:52.000000000 -0500
@@ -41,7 +41,7 @@
 BC_BUILD	= $(PWD)/build/
 BC_CPP     	= g++
 BC_CFLAGS       = -Wall -fno-strict-aliasing -I$(FRAMEWORK_PATH) $(CFLAGS)
-BC_LDFLAGS      = $(LDFLAGS) -l pthread
+BC_LDFLAGS      = $(LDFLAGS) -pthread
 
 
 
diff -uNr bcrypt-1.8-3-orig/mod/bc_cfg.h bcrypt-1.8-3/mod/bc_cfg.h
--- bcrypt-1.8-3-orig/mod/bc_cfg.h	2009-09-14 04:54:14.000000000 -0400
+++ bcrypt-1.8-3/mod/bc_cfg.h	2011-01-07 14:32:51.000000000 -0500
@@ -24,8 +24,6 @@
 #undef __KERNEL_STRICT_NAMES
 #define _LOOSE_KERNEL_NAMES
 
-#include <linux/autoconf.h>
-
 #ifndef CONFIG_MODULES
 #  error You must have kernel with loadable modules support
 #endif
